# Generated by Django 2.2 on 2020-07-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa3edniApp', '0002_auto_20200714_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('uniName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('avgPrice', models.FloatField()),
            ],
        ),
    ]
