# Generated by Django 2.2 on 2020-07-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sa3edniApp', '0003_university'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
