# Generated by Django 2.2 on 2020-07-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sa3edniApp', '0004_auto_20200714_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'universities'},
        ),
    ]
