# Generated by Django 2.2 on 2020-07-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa3edniApp', '0007_auto_20200714_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='stream',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sa3edniApp.Stream'),
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sa3edniApp.Stream'),
        ),
        migrations.AddField(
            model_name='subject',
            name='stream',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sa3edniApp.Stream'),
        ),
    ]
