# Generated by Django 2.2 on 2020-07-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa3edniApp', '0008_auto_20200716_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='stream',
            field=models.CharField(choices=[('Scientific', 'Scientific'), ('Literature', 'Literature')], max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(choices=[('Scientific', 'Scientific'), ('Literature', 'Literature')], max_length=25),
        ),
        migrations.AlterField(
            model_name='subject',
            name='stream',
            field=models.CharField(choices=[('Scientific', 'Scientific'), ('Literature', 'Literature')], max_length=25),
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
