# Generated by Django 2.2 on 2020-07-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa3edniApp', '0011_auto_20200724_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='majorName',
            field=models.CharField(max_length=150),
        ),
    ]
