# Generated by Django 2.2 on 2020-07-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa3edniApp', '0012_auto_20200724_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='minAvg',
            field=models.FloatField(default=60),
        ),
    ]
