# Generated by Django 2.2 on 2020-07-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sa3edniApp', '0013_major_minavg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='avgPrice',
            new_name='price',
        ),
    ]
