# Generated by Django 2.2 on 2020-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa3edniApp', '0014_auto_20200724_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='sa3edniApp/static/images/news'),
        ),
    ]
