# Generated by Django 2.2 on 2020-08-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa3edniApp', '0016_auto_20200802_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='majorType',
            field=models.CharField(default='', max_length=20),
        ),
    ]
